import type { CSSProperties } from "react";

/** Co-located styles for AgentPerformanceView. */
export const s = {
  page: { padding: "24px 28px 48px", display: "flex", flexDirection: "column", gap: 24 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, flexWrap: "wrap" } satisfies CSSProperties,
  headerText: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  h1: { fontSize: 20, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-secondary)", margin: 0 } satisfies CSSProperties,
  tiles: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12 } satisfies CSSProperties,
  partialBadge: { fontSize: 11, color: "var(--warn)", marginTop: 4 } satisfies CSSProperties,
  mostActiveSub: { fontSize: 12, color: "var(--text-muted)", marginTop: 4 } satisfies CSSProperties,
  donutRow: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))", gap: 16 } satisfies CSSProperties,
  donutCard: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 16,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  donutTitle: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  noCost: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  section: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  sectionTitle: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  groupLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    margin: "10px 0 4px",
  } satisfies CSSProperties,
  tableWrap: { overflowX: "auto", border: "1px solid var(--border)", borderRadius: 8 } satisfies CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 } satisfies CSSProperties,
  th: {
    textAlign: "left",
    padding: "10px 12px",
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  td: { padding: "10px 12px", borderBottom: "1px solid var(--border)", verticalAlign: "middle" } satisfies CSSProperties,
  muted: { color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
