import type { CSSProperties } from "react";

/** Co-located styles for ExportWizard + its four step components. */
export const s = {
  progressWrap: { padding: "16px 24px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
  body: { padding: 24 } satisfies CSSProperties,
  stepWrap: { display: "flex", flexDirection: "column", gap: 18 } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  footerSpacer: { flex: 1 } satisfies CSSProperties,

  hintText: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  errorText: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
  warnText: { fontSize: 12, color: "var(--warn)", margin: "6px 0 0" } satisfies CSSProperties,
  note: { fontSize: 12, color: "var(--text-muted)", margin: 0, lineHeight: 1.5 } satisfies CSSProperties,

  // ---- Target step -----------------------------------------------------
  targetGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 10,
  } satisfies CSSProperties,
  targetCardActive: { border: "1.5px solid var(--accent)" } satisfies CSSProperties,
  targetCardDisabled: { opacity: 0.5, cursor: "not-allowed" } satisfies CSSProperties,
  targetCardHead: { display: "flex", alignItems: "center", gap: 8, marginBottom: 6 } satisfies CSSProperties,
  targetCardTitle: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  targetCardDesc: { fontSize: 12, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,
  targetCardReason: { fontSize: 11, color: "var(--text-muted)", margin: "6px 0 0", fontStyle: "italic" } satisfies CSSProperties,

  // ---- Preview step ------------------------------------------------------
  previewLayout: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 260px) minmax(0, 1fr)",
    gap: 16,
    alignItems: "start",
  } satisfies CSSProperties,
  filesHeading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  fileList: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  fileRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid transparent",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
    font: "inherit",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  fileRowActive: {
    background: "var(--bg-hover)",
    border: "1px solid var(--border-strong)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  filePath: { fontSize: 12.5, wordBreak: "break-all" } satisfies CSSProperties,
  fileContent: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 14,
    minHeight: 280,
  } satisfies CSSProperties,
  pre: {
    margin: 0,
    fontSize: 12.5,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,

  // ---- Configure step ------------------------------------------------------
  triggerList: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  triggerPillRow: { display: "flex", flexWrap: "wrap", gap: 8 } satisfies CSSProperties,
  triggerPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: 999,
    border: "1px solid var(--border-strong)",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 13,
    cursor: "pointer",
    font: "inherit",
  } satisfies CSSProperties,
  triggerPillActive: {
    border: "1px solid var(--accent)",
    background: "var(--accent-bg)",
    color: "var(--accent)",
  } satisfies CSSProperties,
  triggerCostList: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  triggerCost: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  radioList: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  radioRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 14,
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  secretsPanel: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  secretsPanelTitle: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  secretRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10 } satisfies CSSProperties,
  secretName: { fontSize: 13, fontFamily: "var(--font-mono, monospace)" } satisfies CSSProperties,
  secretStatus: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,

  // ---- Install step ------------------------------------------------------
  setupLink: { fontSize: 13, color: "var(--accent)" } satisfies CSSProperties,
  installCards: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: 12,
  } satisfies CSSProperties,
  installCard: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  installCardTitle: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  conflictBox: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  conflictTitle: { fontSize: 13, fontWeight: 700, color: "var(--crit)" } satisfies CSSProperties,
  successTitle: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  link: { fontSize: 13, color: "var(--accent)" } satisfies CSSProperties,
  tokenBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 16,
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
  } satisfies CSSProperties,
  tokenBlockTitle: { fontSize: 13, fontWeight: 700 } satisfies CSSProperties,
  tokenValueRow: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  tokenValue: {
    flex: 1,
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-elevated)",
    fontSize: 12.5,
    wordBreak: "break-all",
  } satisfies CSSProperties,
} as const;
