import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page. */
export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  header: { marginBottom: 16 } satisfies CSSProperties,
  headerTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  headerMeta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginTop: 4,
  } satisfies CSSProperties,
  summary: { fontSize: 14, color: "var(--text-secondary)" } satisfies CSSProperties,
  coverage: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  coverageLabel: {
    fontSize: 12,
    color: "var(--text-muted)",
    maxWidth: 220,
    lineHeight: 1.35,
  } satisfies CSSProperties,
  loadingStack: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  layout: {
    display: "grid",
    gridTemplateColumns: "minmax(320px, 420px) 1fr",
    gap: 20,
    alignItems: "start",
  } satisfies CSSProperties,
  listPane: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    maxHeight: "70vh",
    overflowY: "auto",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    textAlign: "left",
    cursor: "pointer",
    width: "100%",
  } satisfies CSSProperties,
  rowActive: {
    border: "1px solid var(--accent)",
    background: "var(--accent-bg)",
  } satisfies CSSProperties,
  rowMain: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 } satisfies CSSProperties,
  rowPath: { fontSize: 13, color: "var(--text-primary)", wordBreak: "break-all" } satisfies CSSProperties,
  rowMeta: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  rowTokens: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  rowUsage: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  previewPane: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 18,
    minHeight: 240,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  outboundNotice: {
    marginTop: 18,
    fontSize: 12,
    color: "var(--text-muted)",
    borderTop: "1px solid var(--border)",
    paddingTop: 12,
  } satisfies CSSProperties,
} as const;
