import type { CSSProperties } from "react";

/** Co-located styles for FindingsPreview (the PR list hover popover). */
export const s = {
  panel: {
    width: 360,
    maxHeight: 380,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  } satisfies CSSProperties,
  content: { flex: 1, minHeight: 0, display: "flex", flexDirection: "column" } satisfies CSSProperties,
  heading: {
    padding: "10px 14px",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  list: {
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
    flex: 1,
    minHeight: 0,
    padding: 6,
    gap: 2,
  } satisfies CSSProperties,
  empty: {
    padding: "18px 14px",
    fontSize: 13,
    color: "var(--text-muted)",
    textAlign: "center",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
    padding: "8px 8px",
    borderRadius: 6,
    border: "none",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowTitleLine: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" } satisfies CSSProperties,
  rowTitle: { fontSize: 13, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  rowMeta: {
    marginTop: 2,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  rowSnippet: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 1.4,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
  } satisfies CSSProperties,
  footer: { borderTop: "1px solid var(--border)", padding: "8px 14px" } satisfies CSSProperties,
  footerLink: {
    background: "none",
    border: "none",
    padding: 0,
    margin: 0,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--accent-text)",
  } satisfies CSSProperties,
} as const;
