import type { CSSProperties } from "react";

/** Co-located styles — same visual language as IntentCard/VerdictBanner. */
export const s = {
  wrap: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    minWidth: 0,
  } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  cardTitle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  cardTitleText: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  describesCommit: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
  } satisfies CSSProperties,
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 10,
  } satisfies CSSProperties,
  emptyTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  emptyBody: {
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    maxWidth: 520,
  } satisfies CSSProperties,
  banner: (color: string, bg: string) =>
    ({
      display: "flex",
      alignItems: "flex-start",
      gap: 10,
      padding: "10px 12px",
      borderRadius: 6,
      border: `1px solid ${color}`,
      background: bg,
      color,
      fontSize: 13,
      lineHeight: 1.45,
    }) satisfies CSSProperties,
  bannerText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  bannerTitle: { fontWeight: 600, color: "var(--text-primary)", marginBottom: 2 } satisfies CSSProperties,
  bannerBody: { color: "var(--text-secondary)" } satisfies CSSProperties,
  riskLevelBadge: (color: string, bg: string) =>
    ({
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      padding: "3px 10px",
      borderRadius: 999,
      border: `1px solid ${color}`,
      background: bg,
      color,
      fontSize: 12,
      fontWeight: 700,
    }) satisfies CSSProperties,
  prose: {
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
    margin: 0,
  } satisfies CSSProperties,
  sectionHeading: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  focusList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  focusItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg)",
    fontSize: 13,
    textAlign: "left",
    cursor: "pointer",
    color: "var(--text-secondary)",
    width: "100%",
  } satisfies CSSProperties,
  focusItemDisabled: {
    cursor: "default",
    opacity: 0.6,
  } satisfies CSSProperties,
  focusPathLine: {
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
    fontSize: 12,
    color: "var(--accent-text)",
    flexShrink: 0,
  } satisfies CSSProperties,
  focusReason: {
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  riskList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  riskRow: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg)",
  } satisfies CSSProperties,
  riskTitleRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  riskExplanation: {
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  riskRefs: {
    fontSize: 11,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
  } satisfies CSSProperties,
  footerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
    paddingTop: 4,
  } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  details: {
    fontSize: 13,
  } satisfies CSSProperties,
  detailsSummary: {
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    userSelect: "none",
  } satisfies CSSProperties,
  inputsList: {
    listStyle: "none",
    margin: 0,
    marginTop: 8,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  inputsRow: {
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  skeletonStack: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
} as const;
