import type { CSSProperties } from "react";

export const s = {
  root: { display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  group: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  groupHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    cursor: "pointer",
    userSelect: "none",
    padding: "4px 2px",
    minWidth: 0,
  } satisfies CSSProperties,
  groupTitleRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
  } satisfies CSSProperties,
  groupTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
    whiteSpace: "nowrap",
    flexShrink: 0,
  } satisfies CSSProperties,
  groupSubtitle: {
    fontSize: 12,
    color: "var(--text-muted)",
    lineHeight: 1.4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  } satisfies CSSProperties,
  groupMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  files: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  summary: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    margin: "0 12px 8px",
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-subtle, var(--bg))",
    border: "1px solid var(--border)",
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  summaryLabel: { fontWeight: 600, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  summaryText: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  } satisfies CSSProperties,
  summaryBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    flexShrink: 0,
    padding: "3px 9px",
    borderRadius: 999,
    border: "1px solid color-mix(in srgb, var(--accent, #3b82f6) 35%, var(--border))",
    background: "color-mix(in srgb, var(--accent, #3b82f6) 14%, transparent)",
    color: "var(--accent-text, #93c5fd)",
    fontSize: 11,
    fontWeight: 600,
    cursor: "pointer",
    textTransform: "lowercase" as const,
  } satisfies CSSProperties,
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
    border: "none",
    padding: 0,
    cursor: "pointer",
  } satisfies CSSProperties,
  banner: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: "14px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  bannerTitle: { fontSize: 14, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  bannerBody: { fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.45 } satisfies CSSProperties,
  splitList: { display: "flex", flexDirection: "column", gap: 6, margin: 0, paddingLeft: 18 } satisfies CSSProperties,
  splitItem: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  roleDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
  } satisfies CSSProperties,
  orderToggle: {
    display: "inline-flex",
    border: "1px solid var(--border)",
    borderRadius: 7,
    overflow: "hidden",
  } satisfies CSSProperties,
  orderBtn: {
    border: "none",
    background: "transparent",
    padding: "5px 10px",
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-muted)",
    cursor: "pointer",
  } satisfies CSSProperties,
  orderBtnActive: {
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  headerRight: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  unavailable: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;

export const ROLE_COLOR: Record<string, string> = {
  core: "var(--accent, #3b82f6)",
  wiring: "var(--sev-warning, #f59e0b)",
  boilerplate: "var(--text-muted)",
};

export const SEVERITY_DOT: Record<string, string> = {
  CRITICAL: "var(--crit, #ef4444)",
  WARNING: "var(--warn, #f59e0b)",
  SUGGESTION: "var(--accent, #3b82f6)",
  INFO: "var(--text-muted)",
};
