import type React from "react";

export const s = {
  card: (accentColor: string): React.CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 10,
    border: "1px solid " + accentColor,
    borderRadius: 10,
    background: "var(--bg-surface)",
    padding: 14,
  }),
  head: { display: "flex", alignItems: "center", gap: 8 } as React.CSSProperties,
  agentName: { fontSize: 14, fontWeight: 600, flex: 1, minWidth: 0 } as React.CSSProperties,
  statusChip: (color: string): React.CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    fontWeight: 600,
    color,
  }),
  meta: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 10, fontSize: 12.5, color: "var(--text-muted)" } as React.CSSProperties,
  errorBox: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 12.5,
    lineHeight: 1.4,
  } as React.CSSProperties,
  footer: { display: "flex", alignItems: "center", justifyContent: "space-between" } as React.CSSProperties,
  footerCount: { fontSize: 12, color: "var(--text-muted)" } as React.CSSProperties,
  findingsList: { display: "flex", flexDirection: "column", gap: 8 } as React.CSSProperties,
  findingRow: { display: "flex", alignItems: "flex-start", gap: 8 } as React.CSSProperties,
  findingMain: { flex: 1, minWidth: 0 } as React.CSSProperties,
  findingTitle: {
    fontSize: 12.5,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } as React.CSSProperties,
  findingLoc: { fontSize: 11.5, color: "var(--text-muted)" } as React.CSSProperties,
};
