import type { CSSProperties } from "react";

/** Co-located styles for IntentCard — matches VerdictBanner / OverviewTab language. */
export const s = {
  wrap: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  // Same visual language as SectionLabel, without its outer marginBottom —
  // title sits inside the card; wrap `gap` owns spacing under it.
  cardTitle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  cardTitleText: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 10,
  } satisfies CSSProperties,
  emptyTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  emptyBody: {
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    maxWidth: 520,
  } satisfies CSSProperties,
  // Mock: italic blockquote — primary objective reads as a quote, not body copy.
  intentText: {
    fontSize: 14,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
    margin: 0,
    fontStyle: "italic",
    borderLeft: "3px solid var(--border)",
    paddingLeft: 14,
  } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  // Always two columns inside the Intent card (mock In | Out side-by-side).
  // Don't use auto-fit/minmax(280px) here — Intent already sits in a half-width
  // Overview column (~400–500px), so 280×2 overflows and collapses to a stack.
  scopeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 16,
  } satisfies CSSProperties,
  scopeCol: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minWidth: 0,
  } satisfies CSSProperties,
  scopeHeading: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  scopeList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  scopeItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  scopeIconIn: { color: "var(--ok)", flexShrink: 0, marginTop: 2 } satisfies CSSProperties,
  // Mock: muted X, not crit red — out-of-scope is an informational label, not
  // a severity signal (see docs/plans/intent-layer.md WI11 gap G3/G4).
  scopeIconOut: { color: "var(--text-muted)", flexShrink: 0, marginTop: 2 } satisfies CSSProperties,
  scopeEmpty: {
    fontSize: 13,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,
  staleBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 13,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  staleText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  staleTitle: { fontWeight: 600, color: "var(--text-primary)", marginBottom: 2 } satisfies CSSProperties,
  staleBody: { color: "var(--text-secondary)" } satisfies CSSProperties,
  // Demoted vs mock primary surfaces (WI11 G5): left accent only — full
  // orange border competed with objective/scope/risks on first paint.
  warnBox: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    padding: "10px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    borderLeft: "3px solid var(--warn)",
    background: "var(--bg)",
  } satisfies CSSProperties,
  warnTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    color: "var(--warn)",
  } satisfies CSSProperties,
  warnList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  warnItem: {
    fontSize: 13,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  warnMore: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,
  // Mock: horizontal pill chips under Risk Areas (not a vertical bullet list).
  riskBlock: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  riskHeading: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  riskPills: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  } satisfies CSSProperties,
  riskPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px",
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "var(--bg)",
    fontSize: 12,
    lineHeight: 1.35,
    color: "var(--text-secondary)",
    fontWeight: 500,
  } satisfies CSSProperties,
  // Demoted below primary surfaces so SectionLabel stays mock-clean.
  metaFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    flexWrap: "wrap",
    paddingTop: 4,
  } satisfies CSSProperties,
  sourcesDetails: {
    fontSize: 13,
  } satisfies CSSProperties,
  sourcesSummary: {
    cursor: "pointer",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    userSelect: "none",
  } satisfies CSSProperties,
  sourceList: {
    listStyle: "none",
    margin: 0,
    marginTop: 8,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  sourceRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  sourceRef: {
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  skeletonStack: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
} as const;
